database.url=jdbc:mysql://localhost:3306/Professional_Practice_System_Pruebas
database.user=root
database.password=011048

mail.user=sistemapracticasprofesionales@gmail.com
mail.password=nlzswpqkesuezoax