database.url=jdbc:mysql://trolley.proxy.rlwy.net:24663/Professional_Practice_System
database.user=Administrador_General
database.password=Qbs1109aaa

mail.user=sistemapracticasprofesionales@gmail.com
mail.password=nlzswpqkesuezoax